# Generated by Django 5.1 on 2024-09-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('delivery_address', models.TextField()),
                ('delivery_time_slot', models.CharField(choices=[('Morning', 'Morning (8 AM - 12 PM)'), ('Afternoon', 'Afternoon (12 PM - 4 PM)'), ('Evening', 'Evening (4 PM - 8 PM)')], default='Morning', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
